# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Peter/Documents/15_16Sophomore/EECE2030/4bitSubtractor/4bitSubtractor.cache/wt [current_project]
set_property parent.project_path C:/Users/Peter/Documents/15_16Sophomore/EECE2030/4bitSubtractor/4bitSubtractor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Peter/Documents/15_16Sophomore/EECE2030/4bitSubtractor/4bitSubtractor.srcs/sources_1/new/fullSubtractor.vhd
  C:/Users/Peter/Documents/15_16Sophomore/EECE2030/4bitSubtractor/4bitSubtractor.srcs/sources_1/new/top_4bitSubtractor.vhd
}
read_xdc C:/Users/Peter/Documents/15_16Sophomore/EECE2030/4bitSubtractor/4bitSubtractor.srcs/constrs_1/imports/EECE2030/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Peter/Documents/15_16Sophomore/EECE2030/4bitSubtractor/4bitSubtractor.srcs/constrs_1/imports/EECE2030/Basys3_Master.xdc]

synth_design -top top_4bitSubtractor -part xc7a35tcpg236-1
write_checkpoint -noxdef top_4bitSubtractor.dcp
catch { report_utilization -file top_4bitSubtractor_utilization_synth.rpt -pb top_4bitSubtractor_utilization_synth.pb }
